DROP TABLE IF EXISTS `FOLLOWING`;
DROP TABLE IF EXISTS `COMMENT`;
DROP TABLE IF EXISTS `LIKES`;
DROP TABLE IF EXISTS `POST`;
DROP TABLE IF EXISTS `HASHTAG`;
DROP TABLE IF EXISTS `PROFILE`;
DROP TABLE IF EXISTS `USER`;

DROP DATABASE IF EXISTS `CHATI_DB`;